spring:
  datasource:
    username: root
    password: 123456
    driverClassName: org.h2.Driver
    url: jdbc:h2:file:./celerity
  sql:
    init:
      platform: h2
  h2:
    console:
      path: /h2
      enabled: true
      settings:
        web-allow-others: true
  devtools:
    restart:
      poll-interval: "2s"
      quiet-period: "1s"
      exclude: "static/**,public/**"
