CREATE TABLE IF NOT EXISTS `uc_user` (
    `id` VARCHAR(32) NOT NULL COMMENT '主键ID' COLLATE 'utf8mb4_unicode_ci',
    `username` VARCHAR(32) NOT NULL DEFAULT '' COMMENT '用户名' COLLATE 'utf8mb4_unicode_ci',
    `password` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '密码' COLLATE 'utf8mb4_unicode_ci',
    `code` VARCHAR(32) NOT NULL COMMENT '编码' COLLATE 'utf8mb4_unicode_ci',
    `name` VARCHAR(32) NOT NULL DEFAULT '' COMMENT '姓名' COLLATE 'utf8mb4_unicode_ci',
    `phone` VARCHAR(11) NULL DEFAULT '' COMMENT '手机' COLLATE 'utf8mb4_unicode_ci',
    `email` VARCHAR(64) NULL DEFAULT '' COMMENT '邮箱' COLLATE 'utf8mb4_unicode_ci',
    `type` TINYINT(3) NULL DEFAULT '1' COMMENT '用户类型',
    `status` TINYINT(3) NULL DEFAULT '0' COMMENT '状态',
    `is_admin` TINYINT(1) NULL DEFAULT '0' COMMENT '是否管理员',
    `salt` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '密码加盐' COLLATE 'utf8mb4_unicode_ci',
    `remark` VARCHAR(255) NULL DEFAULT '' COMMENT '备注' COLLATE 'utf8mb4_unicode_ci',
    `is_valid` TINYINT(1) NULL DEFAULT '1' COMMENT '是否生效',
    `created_by` VARCHAR(32) NULL DEFAULT NULL COMMENT '创建人ID' COLLATE 'utf8mb4_unicode_ci',
    `created_at` DATETIME NULL DEFAULT NULL COMMENT '创建时间',
    `updated_by` VARCHAR(32) NULL DEFAULT NULL COMMENT '更新人ID' COLLATE 'utf8mb4_unicode_ci',
    `updated_at` DATETIME NULL DEFAULT NULL COMMENT '更新时间',
    `deleted_by` VARCHAR(32) NULL DEFAULT NULL COMMENT '删除人ID' COLLATE 'utf8mb4_unicode_ci',
    `deleted_at` DATETIME NULL DEFAULT NULL COMMENT '删除时间',
    PRIMARY KEY (`id`),
    UNIQUE INDEX `code` (`code`),
    UNIQUE INDEX `username` (`username`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
