version: "3.9"
services:
  mongo:
    image: mongo:6.0.5
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - ./mongo/config:/etc/mongo
      - ./mongo/data:/data/db
    ports:
      - "27017:27017"
    hostname: mongo
    networks:
      - store
    privileged: true
    restart: always
    user: root
    command: mongo --config /etc/mongo/mongod.conf

  mysql:
    image: mysql:8.0.33
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "celerity"
    volumes:
      - ./mysql/config:/etc/mysql/conf.d
      - ./mysql/data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    hostname: mysql
    networks:
      - store
    privileged: true
    restart: always
    user: root
    command: --default-authentication-plugin=mysql_native_password

  orientdb:
    image: orientdb:3.2.18
    environment:
      ORIENTDB_ROOT_PASSWORD: "root"
      ORIENTDB_NODE_NAME: "odb1"
    volumes:
      - ./orientdb/config:/orientdb/config
      - ./orientdb/data:/orientdb/databases
      - ./orientdb/backup:/orientdb/backup
    ports:
      - "2424:2424"
      - "2480:2480"
    hostname: orientdb
    networks:
      - store
    privileged: true
    restart: always
    user: root
    command: /orientdb/bin/server.sh -Xmx8g -Ddistributed=true

networks:
  store:
    ipam:
      driver: default
      config:
        - subnet: 10.10.0.0/24
