version: "3.9"
services:
  apisix:
    image: apache/apisix:latest
    environment:
      APISIX_STAND_ALONE: true
      ALLOW_NONE_AUTHENTICATION: "yes"
    volumes:
      - ./apisix/config/config.yaml:/usr/local/apisix/conf/config.yaml
      - ./apisix/logs:/usr/local/apisix/logs
    ports:
      - "9080:9080"
    hostname: apisix
    networks:
      - gateway
    privileged: true
    restart: always
    user: root

networks:
  gateway:
    ipam:
      driver: default
      config:
        - subnet: 20.10.0.0/24
